apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ml-model
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000
