apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-release3-ingress
spec:
  rules:
    - host: ml-release2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: model-service
                port:
                  number: 5000