apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-ml-model-deployment   # Match this with your Deployment's label
  ports:
    - protocol: TCP
      port: 80                       # The port that your service will expose
      targetPort: 5000               # The port your container is listening on
  type: {{ .Values.service.type }}    # Can be "ClusterIP", "LoadBalancer", "NodePort"
